# WAP to perform all the string methods

st = "Hello, my name is Hemant. Current {house_no: 3f}"
print("Capitalize -->", st.capitalize())
print("Casefold -->", st.casefold())
print("Center -->", st.center(20))
print("Count 'm' -->", st.count("m", 0, len(st)))
print("Encode -->", st.encode())
print("Endswith 'd' -->", st.endswith("d"))
print("Expandtabs by 4 -->", st.expandtabs(4))
print("Find 'Hemant' -->", st.find('Hemant'))
print("Format 'year to 2002' -->", st.format(house_no = 223))
print("index -->", st.index("is"))
print("isalnum -->", st.isalnum())
print("isalpha -->", st.isalpha())
print("isascii -->", st.isascii())
print("isdecimal -->", st.isdecimal())
print("isdigit -->", st.isdigit())
print("isidentifier -->", st.isidentifier())
print("islower -->", st.islower())
print("isnumeric -->", st.isnumeric())
print("isprintable -->", st.isprintable())
print("isspace -->", st.isspace())
print("istitle -->", st.istitle())
print("isupper -->", st.isupper())
print("join '#' to given string -->", "#".join(st))
print("ljust -->", st.ljust(15))
print("lower -->", st.lower())
print("lstrip -->", st.lstrip())

print("maketraps -->", st.translate(st.maketrans("is", "::")))
print("partition -->", st.partition("Hello"))
print("replace -->", st.replace("Hello", "Aloha"))
print("rfind -->", st.rfind("name"))
print("rindex -->", st.rindex("Hemant"))
print("rjust -->", st.rjust(20))
print("rpartition -->", st.rpartition("Hemant"))
print("rsplit -->", st.rsplit("."))
print("rstrip -->", st.rstrip())
print("split -->", st.split(","))
print("splitlines -->", st.splitlines())
print("startswith -->", st.startswith("Hello"))
print("strip -->", st.strip())
print("swapcase -->", st.swapcase())
print("title -->", st.title())
print("translate -->", st.translate(st.maketrans("b", "B")))
print("upper -->", st.upper())
print("zfill -->", st.zfill(len(st)))
